"""initial schema

Revision ID: 8a61938ec60f
Revises: 
Create Date: 2026-07-05 09:58:49.777670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a61938ec60f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(length=255), nullable=False),
    sa.Column('telethon_phone_code_hash', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_sessions_tenant_id'), 'login_sessions', ['tenant_id'], unique=False)
    op.create_table('telegram_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash_encrypted', sa.Text(), nullable=False),
    sa.Column('session_encrypted', sa.Text(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('flood_wait_until', sa.DateTime(), nullable=True),
    sa.Column('last_profile_edit_at', sa.DateTime(), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_accounts_tenant_id'), 'telegram_accounts', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auto_reply_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.Column('replied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_reply_log_account_id'), 'auto_reply_log', ['account_id'], unique=False)
    op.create_index(op.f('ix_auto_reply_log_peer_id'), 'auto_reply_log', ['peer_id'], unique=False)
    op.create_table('auto_reply_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_reply_rules_account_id'), 'auto_reply_rules', ['account_id'], unique=True)
    op.create_table('bulk_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_template', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_jobs_tenant_id'), 'bulk_jobs', ['tenant_id'], unique=False)
    op.create_table('cached_dialogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.Column('peer_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('photo_thumb_b64', sa.Text(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_text', sa.Text(), nullable=True),
    sa.Column('last_message_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_dialogs_account_id'), 'cached_dialogs', ['account_id'], unique=False)
    op.create_table('bulk_job_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('payload_override', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('flood_wait_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['bulk_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_job_items_account_id'), 'bulk_job_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_bulk_job_items_job_id'), 'bulk_job_items', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bulk_job_items_job_id'), table_name='bulk_job_items')
    op.drop_index(op.f('ix_bulk_job_items_account_id'), table_name='bulk_job_items')
    op.drop_table('bulk_job_items')
    op.drop_index(op.f('ix_cached_dialogs_account_id'), table_name='cached_dialogs')
    op.drop_table('cached_dialogs')
    op.drop_index(op.f('ix_bulk_jobs_tenant_id'), table_name='bulk_jobs')
    op.drop_table('bulk_jobs')
    op.drop_index(op.f('ix_auto_reply_rules_account_id'), table_name='auto_reply_rules')
    op.drop_table('auto_reply_rules')
    op.drop_index(op.f('ix_auto_reply_log_peer_id'), table_name='auto_reply_log')
    op.drop_index(op.f('ix_auto_reply_log_account_id'), table_name='auto_reply_log')
    op.drop_table('auto_reply_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telegram_accounts_tenant_id'), table_name='telegram_accounts')
    op.drop_table('telegram_accounts')
    op.drop_index(op.f('ix_login_sessions_tenant_id'), table_name='login_sessions')
    op.drop_table('login_sessions')
    # ### end Alembic commands ###
